# Archivo: .github/workflows/build-and-release.yml

name: Build and Release JavaFX App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean javafx:jlink

      - name: Compress Linux package
        run: |
          cd ./target
          zip -r papasoft_linux.zip papasoft_image/

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/papasoft_linux.zip
          asset_name: papasoft-client-linux-v1.0.${{ github.run_number }}.zip
          asset_content_type: application/zip

  build-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven (Windows)
        run: mvn clean javafx:jlink

      - name: Compress Windows package
        run: |
          Compress-Archive -Path target/papasoft_image/* -DestinationPath target/papasoft_windows.zip

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/papasoft_windows.zip
          asset_name: papasoft-client-windows-v1.0.${{ github.run_number }}.zip
          asset_content_type: application/zip